import {
  IconChartBar,
  IconDashboard,
  IconFolder,
  IconListDetails,
  IconUsers,
  IconUsersGroup,
} from "@tabler/icons-react";
import adminAvatar from "../asset/admin.png";

const venders = [
  {
    id: 1,
    header: "Shree Balaji Kirana Store",
    status: "Open",
    target: "50000",
    limit: "10000",
  },
  {
    id: 2,
    header: "Green Leaf Grocery",
    status: "Open",
    target: "75000",
    limit: "15000",
  },
  {
    id: 3,
    header: "Ravi General Stores",
    status: "Closed",
    target: "40000",
    limit: "8000",
  },
  {
    id: 4,
    header: "Daily Needs Mart",
    status: "Open",
    target: "90000",
    limit: "20000",
  },
  {
    id: 5,
    header: "Fresh Basket Grocery",
    status: "Temporarily Closed",
    target: "65000",
    limit: "12000",
  },
  {
    id: 6,
    header: "Kirana King",
    status: "Open",
    target: "85000",
    limit: "17000",
  },
  {
    id: 7,
    header: "Om Sai Supermart",
    status: "Open",
    target: "100000",
    limit: "25000",
  },
  {
    id: 8,
    header: "Navbharat Provisions",
    status: "Closed",
    target: "55000",
    limit: "11000",
  },
  {
    id: 9,
    header: "City Fresh Grocers",
    status: "Open",
    target: "95000",
    limit: "18000",
  },
  {
    id: 10,
    header: "Sundar Kirana Bhandar",
    status: "Open",
    target: "70000",
    limit: "14000",
  },
];

const orders = [
  {
    id: 1,
    header: "Order #1001 - Fruits & Vegetables",
    status: "Delivered",
    target: "1200",
    limit: "500",
  },
  {
    id: 2,
    header: "Order #1002 - Dairy Essentials",
    status: "Pending",
    target: "800",
    limit: "300",
  },
  {
    id: 3,
    header: "Order #1003 - Whole Grains",
    status: "Cancelled",
    target: "1500",
    limit: "600",
  },
  {
    id: 4,
    header: "Order #1004 - Snacks & Beverages",
    status: "Delivered",
    target: "2200",
    limit: "750",
  },
  {
    id: 5,
    header: "Order #1005 - Spices & Masala",
    status: "Shipped",
    target: "950",
    limit: "400",
  },
  {
    id: 6,
    header: "Order #1006 - Bakery Items",
    status: "Delivered",
    target: "1150",
    limit: "500",
  },
  {
    id: 7,
    header: "Order #1007 - Monthly Grocery Pack",
    status: "Processing",
    target: "3000",
    limit: "1000",
  },
  {
    id: 8,
    header: "Order #1008 - Cold Storage Items",
    status: "Returned",
    target: "1700",
    limit: "600",
  },
  {
    id: 9,
    header: "Order #1009 - Personal Care Bundle",
    status: "Pending",
    target: "1300",
    limit: "450",
  },
  {
    id: 10,
    header: "Order #1010 - Mixed Household Order",
    status: "Delivered",
    target: "2600",
    limit: "900",
  },
];

const products = [
  {
    id: 1,
    header: "Fresh Produce",
    status: "In Stock",
    target: "150",
    limit: "50",
  },
  {
    id: 2,
    header: "Dairy Products",
    status: "Low Stock",
    target: "100",
    limit: "30",
  },
  {
    id: 3,
    header: "Bakery Items",
    status: "In Stock",
    target: "80",
    limit: "20",
  },
  {
    id: 4,
    header: "Meat & Poultry",
    status: "Out of Stock",
    target: "120",
    limit: "40",
  },
  {
    id: 5,
    header: "Frozen Foods",
    status: "In Stock",
    target: "200",
    limit: "60",
  },
  {
    id: 6,
    header: "Beverages",
    status: "In Stock",
    target: "180",
    limit: "70",
  },
  {
    id: 7,
    header: "Snacks & Confectionery",
    status: "Low Stock",
    target: "140",
    limit: "50",
  },
  {
    id: 8,
    header: "Household Supplies",
    status: "In Stock",
    target: "90",
    limit: "25",
  },
  {
    id: 9,
    header: "Personal Care",
    status: "In Stock",
    target: "110",
    limit: "35",
  },
  {
    id: 10,
    header: "Organic & Specialty",
    status: "Out of Stock",
    target: "60",
    limit: "15",
  },
];

const transactions = [
  {
    id: 1,
    header: "Txn #TX1001 - Payment for Order #1001",
    status: "Success",
    target: "1200",
    limit: "10000",
  },
  {
    id: 2,
    header: "Txn #TX1002 - Refund for Cancelled Order #1003",
    status: "Success",
    target: "1500",
    limit: "10000",
  },
  {
    id: 3,
    header: "Txn #TX1003 - Wallet Top-up",
    status: "Pending",
    target: "2000",
    limit: "5000",
  },
  {
    id: 4,
    header: "Txn #TX1004 - COD Collection",
    status: "Success",
    target: "2200",
    limit: "15000",
  },
  {
    id: 5,
    header: "Txn #TX1005 - Failed UPI Payment",
    status: "Failed",
    target: "900",
    limit: "10000",
  },
  {
    id: 6,
    header: "Txn #TX1006 - Vendor Payout",
    status: "Success",
    target: "5000",
    limit: "25000",
  },
  {
    id: 7,
    header: "Txn #TX1007 - Delivery Partner Settlement",
    status: "Pending",
    target: "1300",
    limit: "10000",
  },
  {
    id: 8,
    header: "Txn #TX1008 - Reversal of Extra Charge",
    status: "Success",
    target: "150",
    limit: "5000",
  },
  {
    id: 9,
    header: "Txn #TX1009 - Payment for Order #1009",
    status: "Success",
    target: "1300",
    limit: "15000",
  },
  {
    id: 10,
    header: "Txn #TX1010 - Subscription Renewal",
    status: "Failed",
    target: "999",
    limit: "3000",
  },
];

const users = [
  {
    id: 1,
    header: "Rohit Sharma",
    status: "Active",
    target: "3200",
    limit: "5000",
  },
  {
    id: 2,
    header: "Anjali Mehta",
    status: "Active",
    target: "1500",
    limit: "4000",
  },
  {
    id: 3,
    header: "Suresh Kumar",
    status: "Inactive",
    target: "600",
    limit: "3000",
  },
  {
    id: 4,
    header: "Fatima Sheikh",
    status: "Banned",
    target: "0",
    limit: "1000",
  },
  {
    id: 5,
    header: "Vikram Desai",
    status: "Active",
    target: "5000",
    limit: "7000",
  },
  {
    id: 6,
    header: "Neha Agarwal",
    status: "Active",
    target: "2100",
    limit: "5000",
  },
  {
    id: 7,
    header: "Prakash Yadav",
    status: "Inactive",
    target: "950",
    limit: "3500",
  },
  {
    id: 8,
    header: "Divya Patel",
    status: "Active",
    target: "4300",
    limit: "6000",
  },
  {
    id: 9,
    header: "Amitabh Joshi",
    status: "Banned",
    target: "100",
    limit: "2000",
  },
  {
    id: 10,
    header: "Sneha Nair",
    status: "Active",
    target: "3000",
    limit: "5000",
  },
];

const societies = [
  {
    id: 1,
    header: "Green Valley Residency",
    status: "Active",
    target: "100000",
    limit: "20000",
  },
  {
    id: 2,
    header: "Sunshine Apartments",
    status: "Active",
    target: "80000",
    limit: "15000",
  },
  {
    id: 3,
    header: "Silver Oak Society",
    status: "Inactive",
    target: "60000",
    limit: "12000",
  },
  {
    id: 4,
    header: "Maple Heights",
    status: "Active",
    target: "95000",
    limit: "18000",
  },
  {
    id: 5,
    header: "Royal Greens",
    status: "Blacklisted",
    target: "0",
    limit: "15000",
  },
  {
    id: 6,
    header: "Blue Sky Towers",
    status: "Active",
    target: "110000",
    limit: "22000",
  },
  {
    id: 7,
    header: "Harmony Enclave",
    status: "Active",
    target: "72000",
    limit: "14000",
  },
  {
    id: 8,
    header: "Sai Dham Housing",
    status: "Inactive",
    target: "50000",
    limit: "10000",
  },
  {
    id: 9,
    header: "Lake View Residency",
    status: "Active",
    target: "85000",
    limit: "17000",
  },
  {
    id: 10,
    header: "Prestige Gardenia",
    status: "Active",
    target: "120000",
    limit: "25000",
  },
];

const sideBardata = {
  user: {
    name: "admin",
    email: process.env.NEXT_PUBLIC_ADMIN_USERNAME || "",
    avatar: adminAvatar.src,
  },
  navMain: [
    {
      title: "Vendors",
      url: "#",
      icon: IconDashboard,
      data: venders,
    },
    {
      title: "Orders",
      url: "#",
      icon: IconListDetails,
      data: orders,
    },
    {
      title: "Products",
      url: "#",
      icon: IconChartBar,
      data: products,
    },
    {
      title: "Transactions",
      url: "#",
      icon: IconFolder,
      data: transactions,
    },
    {
      title: "Users",
      url: "#",
      icon: IconUsers,
      data: users,
    },
    {
      title: "Societies",
      url: "#",
      icon: IconUsersGroup,
      data: societies,
    },
  ],
};

export { sideBardata };
